---keymaps
vim.keymap.set("n", "<leader>s", ":w<CR>")
vim.keymap.set("n", "<leader>q", ":q<CR>")
vim.keymap.set("n", "<leader>e", ":Oil<CR>")
vim.keymap.set("n", "<leader>ff", ":Telescope fd<CR>")
vim.keymap.set("n", "<leader>fr", ":Telescope oldfiles<CR>")
vim.keymap.set("n", "<leader>fb", ":Telescope buffers<CR>")
vim.keymap.set("n", "<leader>bb", ":enew<CR>")
vim.keymap.set("n", "<leader>bd", ":bd<CR>")
vim.keymap.set("n", "<leader>bt", ":Trouble diagnostics<CR>")
vim.keymap.set("t", "<C-l>", "<C-\\><C-n>")
vim.keymap.set("i", "<C-l>", "<Esc>")
vim.keymap.set("n", "U", "<C-r>")
vim.keymap.set("n", "<leader>wt", ":cd %:p:h<CR> :sp<CR> :terminal<CR>")
vim.keymap.set("n", "<leader>wc", ":cd %:p:h<CR>")
vim.keymap.set("n", "zR", ":openAllFolds<CR>")
vim.keymap.set("n", "zM", ":closeAllFolds<CR>")
vim.keymap.set("n", "<leader>bo", ":BufDelOthers<CR>")
--window management
vim.keymap.set("n", "<leader>ws", ":sp<CR>")
vim.keymap.set("n", "<leader>wv", ":vsp<CR>")
vim.keymap.set("n", "<leader>h", "<C-w>h")
vim.keymap.set("n", "<leader>j", "<C-w>j")
vim.keymap.set("n", "<leader>k", "<C-w>k")
vim.keymap.set("n", "<leader>l", "<C-w>l")
vim.keymap.set("n", "<leader>c", "<C-w>c")
