return {
	{ "https://github.com/nvim-lua/plenary.nvim" },
	{ "https://github.com/stevearc/oil.nvim", lazy = false },
	{ "https://github.com/nvim-telescope/telescope.nvim", lazy = false },
	{ "https://github.com/nvim-mini/mini.icons", opts = {}, lazy = false },
	{ "https://github.com/stevearc/conform.nvim", lazy = false },
	{ "https://github.com/nvim-treesitter/nvim-treesitter", lazy = false },
	{ "https://github.com/folke/trouble.nvim", opts = {}, lazy = false },
	{ "https://github.com/adelarsq/image_preview.nvim", opts = {}, lazy = false },
	{ "https://github.com/kevinhwang91/nvim-ufo", lazy = false },
	{ "https://github.com/kevinhwang91/promise-async", lazy = false },
	{ "https://github.com/EdenEast/nightfox.nvim", lazy = false },
	{ "https://github.com/neovim/nvim-lspconfig", lazy = false },
	{ "https://github.com/mason-org/mason.nvim", opts = {}, lazy = false },
	{ "https://github.com/mason-org/mason-lspconfig.nvim", opts = {}, lazy = false },
	{ "https://github.com/WhoIsSethDaniel/mason-tool-installer.nvim", lazy = false },
	{ "https://github.com/Saghen/blink.cmp", lazy = false },
}
